TARGET_ARCH = linux

CC     = g++
OPT    = -O3
DEBUG  = -g
OTHER  = -Wall -Wno-deprecated
# CFLAGS = $(DEBUG) $(OTHER)
CFLAGS = $(OPT) $(OTHER)

MODULE = run
SRCS = TRouter.cpp TProcessingElement.cpp main.cpp
OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs
