TARGET_ARCH = linux
CC     = g++
OPT    = -O2 # -O3
DEBUG  = -g
OTHER  = -Wall -Wno-deprecated
CFLAGS = $(OPT) $(OTHER)
#CFLAGS = $(DEBUG) $(OPT) $(OTHER)

MODULE = noxim
SRCS = TNoC.cpp TRouter.cpp TProcessingElement.cpp TBuffer.cpp TStats.cpp \
	TGlobalStats.cpp TGlobalRoutingTable.cpp TLocalRoutingTable.cpp \
	TGlobalTrafficTable.cpp TReservationTable.cpp main.cpp
OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs

# DO NOT DELETE

TBuffer.o: TBuffer.h NoximDefs.h
TGlobalRoutingTable.o: /usr/include/stdio.h /usr/include/features.h
TGlobalRoutingTable.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
TGlobalRoutingTable.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
TGlobalRoutingTable.o: /usr/include/bits/typesizes.h /usr/include/libio.h
TGlobalRoutingTable.o: /usr/include/_G_config.h /usr/include/wchar.h
TGlobalRoutingTable.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TGlobalRoutingTable.o: /usr/include/bits/stdio_lim.h
TGlobalRoutingTable.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TGlobalRoutingTable.o: /usr/include/string.h NoximDefs.h
TGlobalRoutingTable.o: TGlobalRoutingTable.h
TGlobalStats.o: TGlobalStats.h TNoC.h TTile.h TRouter.h NoximDefs.h TBuffer.h
TGlobalStats.o: TStats.h TGlobalRoutingTable.h TLocalRoutingTable.h
TGlobalStats.o: TReservationTable.h TProcessingElement.h
TGlobalStats.o: TGlobalTrafficTable.h /usr/include/stdio.h
TGlobalStats.o: /usr/include/features.h /usr/include/sys/cdefs.h
TGlobalStats.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
TGlobalStats.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
TGlobalStats.o: /usr/include/libio.h /usr/include/_G_config.h
TGlobalStats.o: /usr/include/wchar.h /usr/include/bits/wchar.h
TGlobalStats.o: /usr/include/gconv.h /usr/include/bits/stdio_lim.h
TGlobalStats.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TGlobalTrafficTable.o: TGlobalTrafficTable.h /usr/include/stdio.h
TGlobalTrafficTable.o: /usr/include/features.h /usr/include/sys/cdefs.h
TGlobalTrafficTable.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
TGlobalTrafficTable.o: /usr/include/bits/wordsize.h
TGlobalTrafficTable.o: /usr/include/bits/typesizes.h /usr/include/libio.h
TGlobalTrafficTable.o: /usr/include/_G_config.h /usr/include/wchar.h
TGlobalTrafficTable.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TGlobalTrafficTable.o: /usr/include/bits/stdio_lim.h
TGlobalTrafficTable.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TGlobalTrafficTable.o: NoximDefs.h
TLocalRoutingTable.o: TLocalRoutingTable.h TGlobalRoutingTable.h NoximDefs.h
TNoC.o: TNoC.h TTile.h TRouter.h NoximDefs.h TBuffer.h TStats.h
TNoC.o: TGlobalRoutingTable.h TLocalRoutingTable.h TReservationTable.h
TNoC.o: TProcessingElement.h TGlobalTrafficTable.h /usr/include/stdio.h
TNoC.o: /usr/include/features.h /usr/include/sys/cdefs.h
TNoC.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
TNoC.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
TNoC.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
TNoC.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TNoC.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
TNoC.o: /usr/include/stdlib.h
TProcessingElement.o: TProcessingElement.h NoximDefs.h TGlobalTrafficTable.h
TProcessingElement.o: /usr/include/stdio.h /usr/include/features.h
TProcessingElement.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
TProcessingElement.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
TProcessingElement.o: /usr/include/bits/typesizes.h /usr/include/libio.h
TProcessingElement.o: /usr/include/_G_config.h /usr/include/wchar.h
TProcessingElement.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TProcessingElement.o: /usr/include/bits/stdio_lim.h
TProcessingElement.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TReservationTable.o: NoximDefs.h TReservationTable.h
TRouter.o: TRouter.h NoximDefs.h TBuffer.h TStats.h TGlobalRoutingTable.h
TRouter.o: TLocalRoutingTable.h TReservationTable.h
TStats.o: TStats.h NoximDefs.h
main.o: NoximDefs.h TNoC.h TTile.h TRouter.h TBuffer.h TStats.h
main.o: TGlobalRoutingTable.h TLocalRoutingTable.h TReservationTable.h
main.o: TProcessingElement.h TGlobalTrafficTable.h /usr/include/stdio.h
main.o: /usr/include/features.h /usr/include/sys/cdefs.h
main.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
main.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
main.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
main.o: /usr/include/bits/wchar.h /usr/include/gconv.h
main.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
main.o: /usr/include/stdlib.h TGlobalStats.h
TBuffer.o: NoximDefs.h
TGlobalStats.o: TNoC.h TTile.h TRouter.h NoximDefs.h TBuffer.h TStats.h
TGlobalStats.o: TGlobalRoutingTable.h TLocalRoutingTable.h
TGlobalStats.o: TReservationTable.h TProcessingElement.h
TGlobalStats.o: TGlobalTrafficTable.h /usr/include/stdio.h
TGlobalStats.o: /usr/include/features.h /usr/include/sys/cdefs.h
TGlobalStats.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
TGlobalStats.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
TGlobalStats.o: /usr/include/libio.h /usr/include/_G_config.h
TGlobalStats.o: /usr/include/wchar.h /usr/include/bits/wchar.h
TGlobalStats.o: /usr/include/gconv.h /usr/include/bits/stdio_lim.h
TGlobalStats.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TGlobalTrafficTable.o: /usr/include/stdio.h /usr/include/features.h
TGlobalTrafficTable.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
TGlobalTrafficTable.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
TGlobalTrafficTable.o: /usr/include/bits/typesizes.h /usr/include/libio.h
TGlobalTrafficTable.o: /usr/include/_G_config.h /usr/include/wchar.h
TGlobalTrafficTable.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TGlobalTrafficTable.o: /usr/include/bits/stdio_lim.h
TGlobalTrafficTable.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TGlobalTrafficTable.o: NoximDefs.h
TLocalRoutingTable.o: TGlobalRoutingTable.h
TNoC.o: TTile.h TRouter.h NoximDefs.h TBuffer.h TStats.h
TNoC.o: TGlobalRoutingTable.h TLocalRoutingTable.h TReservationTable.h
TNoC.o: TProcessingElement.h TGlobalTrafficTable.h /usr/include/stdio.h
TNoC.o: /usr/include/features.h /usr/include/sys/cdefs.h
TNoC.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
TNoC.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
TNoC.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
TNoC.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TNoC.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
TNoC.o: /usr/include/stdlib.h
TProcessingElement.o: NoximDefs.h TGlobalTrafficTable.h /usr/include/stdio.h
TProcessingElement.o: /usr/include/features.h /usr/include/sys/cdefs.h
TProcessingElement.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
TProcessingElement.o: /usr/include/bits/wordsize.h
TProcessingElement.o: /usr/include/bits/typesizes.h /usr/include/libio.h
TProcessingElement.o: /usr/include/_G_config.h /usr/include/wchar.h
TProcessingElement.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TProcessingElement.o: /usr/include/bits/stdio_lim.h
TProcessingElement.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
TRouter.o: NoximDefs.h TBuffer.h TStats.h TGlobalRoutingTable.h
TRouter.o: TLocalRoutingTable.h TReservationTable.h
TStats.o: NoximDefs.h
TTile.o: TRouter.h NoximDefs.h TBuffer.h TStats.h TGlobalRoutingTable.h
TTile.o: TLocalRoutingTable.h TReservationTable.h TProcessingElement.h
TTile.o: TGlobalTrafficTable.h /usr/include/stdio.h /usr/include/features.h
TTile.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
TTile.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
TTile.o: /usr/include/bits/typesizes.h /usr/include/libio.h
TTile.o: /usr/include/_G_config.h /usr/include/wchar.h
TTile.o: /usr/include/bits/wchar.h /usr/include/gconv.h
TTile.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
TTile.o: /usr/include/stdlib.h
